FROM centos:7
ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/ \
    && for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -vf $i; done); \
    rm -vf /lib/systemd/system/multi-user.target.wants/* \
        /etc/systemd/system/*.wants/* \
        /lib/systemd/system/local-fs.target.wants/* \
        /lib/systemd/system/sockets.target.wants/*udev* \
        /lib/systemd/system/sockets.target.wants/*initctl* \
        /lib/systemd/system/basic.target.wants/* \
        /lib/systemd/system/anaconda.target.wants/*

RUN yum install -y -q openssh-server cronie \
    && echo '123qwe' | passwd root --stdin

VOLUME /sys/fs/cgroup
CMD /usr/sbin/init
