---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}.yml"
    - "setup-{{ ansible_os_family }}.yml"
    - "setup-UnsupportedOS.yml"

- include_tasks: "letsencrypt/main.yml"

- import_tasks: vhosts.yml

- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
